import { NextPageContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { TicketsService } from '../services';
import { Ticket, ComponentProps } from '../types';

const Home = ({ tickets }: ComponentProps) => {

  const ticketList = tickets?.map((ticket: Ticket) => {
    return (
      <tr key={ticket.id}>
        <td>{ticket.title}</td>
        <td>{ticket.price}</td>
        <td>
          <Link href="/tickets/[ticketId]" as={`/tickets/${ticket.id}`}>
            <a>Ticket info</a>
          </Link>
        </td>
      </tr>
    );
  });

  return (
    <div >
      <Head>
        <title>Ticket Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div>
        <h1>Tickets</h1>
        {tickets?.length ? (
          <table className="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Price</th>
                <th>View More</th>
              </tr>
            </thead>
            <tbody>{ticketList}</tbody>
          </table>
        ) : <div>We does not have tickets to show</div>}
      </div>
      </main>
    </div>
  );
};

Home.getInitialProps = async (context: NextPageContext) => {
  const allTickets = await new TicketsService().getAll(context) || [];

  return {
    tickets: allTickets ,
  };
};

export default Home;
