name: tests-payments-service

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd payments && npm ci
      - name: Run Linter
        run: cd payments && npm run lint:check
      - name: Check Format Code
        run: cd payments && npm run format:check
      - name: Run Tests
        run: cd payments && npm run test:ci
