name: tests-auth-service

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd auth && npm install
      - name: Run Linter
        run: cd auth && lint:check
      - name: Check Format Code
        run: cd auth && format:check
      - name: Run Tests
        run: cd auth && npm run test:ci
