name: tests-auth-service

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: cd auth && npm ci
      - name: Run Linter
        run: cd auth && npm run lint:check
      - name: Check Format Code
        run: cd auth && npm run format:check
      - name: Run Tests
        run: cd auth && npm run test:ci
